import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';

// Lazy load openai so it doesn't fail Next.js build when OPENAI_API_KEY is missing locally

export async function POST(req: NextRequest) {
  try {
    const { numQuestions, difficulty } = await req.json();

    if (!numQuestions || !difficulty) {
      return NextResponse.json({ error: 'Missing parameters' }, { status: 400 });
    }

    const openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });

    const systemPrompt = `You are a database systems professor. Generate a Multiple Choice Question (MCQ) quiz about Bitmap Indexes.
Requirements:
- Topic: Bitmap Indexes in Database Management Systems (DBMS).
- Number of questions: ${numQuestions}.
- Difficulty: ${difficulty}.
- Provide exactly 4 options per question.
- Format the output strictly as a JSON array of objects.

JSON Format:
{
  "questions": [
    {
      "id": "ai_1",
      "question": "Question text...",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "correctAnswerIndex": 0,
      "explanation": "Brief explanation of why this is correct.",
      "source": "Generated by AI"
    }
  ]
}
`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: "Generate the quiz now." }
      ],
      response_format: { type: "json_object" }, // we might need to wrap in { questions: [] } for json_object to work reliably
    });

    const content = completion.choices[0].message.content || '{"questions":[]}';
    let data;
    try {
      data = JSON.parse(content);
    } catch (e) {
      // If the LLM just returned an array directly despite json_object
      const arrayMatch = content.match(/\\[[\\s\\S]*\\]/);
      if (arrayMatch) {
         data = JSON.parse(arrayMatch[0]);
      } else {
         throw e;
      }
    }

    // Ensure we return an array
    const questions = Array.isArray(data) ? data : (data.questions || []);

    return NextResponse.json({ questions });
  } catch (error) {
    console.error('Quiz Generation Error:', error);
    return NextResponse.json({ error: 'Failed to generate quiz' }, { status: 500 });
  }
}
