export type Question = {
  id: string;
  question: string;
  options: string[];
  correctAnswerIndex: number;
  explanation: string;
  source?: string; // e.g. "GATE CS 2018", "Generated by AI"
};

export const PYQ_BANK: Question[] = [
  {
    id: "pyq_1",
    question: "Which of the following scenarios is most suitable for creating a Bitmap Index?",
    options: [
      "A column with highly unique values like Social Security Numbers.",
      "A column with a small number of distinct values (low cardinality) like Gender or Status.",
      "A primary key column in an OLTP database.",
      "A column containing long variable-length text data."
    ],
    correctAnswerIndex: 1,
    explanation: "Bitmap indexes are highly efficient for low-cardinality columns because each distinct value requires its own bitmap. High cardinality would result in too many sparse bitmaps.",
    source: "GATE CS 2018"
  },
  {
    id: "pyq_2",
    question: "In a database, which boolean operations are primarily used by the engine when combining multiple Bitmap Indexes to resolve a query?",
    options: [
      "JOIN, UNION, INTERSECT",
      "AND, OR, NOT",
      "ADD, SUBTRACT, MULTIPLY",
      "XOR, NAND, NOR"
    ],
    correctAnswerIndex: 1,
    explanation: "Bitmap indexes shine because multiple conditions can be resolved simultaneously using hardware-optimized bitwise AND, OR, and NOT operations.",
    source: "ISRO Scientist (CS) 2016"
  },
  {
    id: "pyq_3",
    question: "Why are Bitmap Indexes typically avoided in high-throughput OLTP (Online Transaction Processing) systems?",
    options: [
      "They consume too much disk space compared to B-Trees.",
      "They cannot handle numeric data types.",
      "Row updates/inserts require locking the entire bitmap, leading to severe concurrency issues.",
      "They are not supported by standard SQL."
    ],
    correctAnswerIndex: 2,
    explanation: "Because a single bitmap represents a value across many rows, updating a single row can lock the bitmap, blocking other concurrent transactions from updating rows that share that value.",
    source: "UGC NET CS 2019"
  },
  {
    id: "pyq_4",
    question: "Which compression algorithm is most commonly used to compress sparse Bitmap Indexes in modern databases?",
    options: [
      "Huffman Coding",
      "Run-Length Encoding (RLE)",
      "Lempel-Ziv-Welch (LZW)",
      "Deflate"
    ],
    correctAnswerIndex: 1,
    explanation: "Run-Length Encoding (like Word-Aligned Hybrid or Roaring Bitmaps) is highly effective for sparse bitmaps because it can compress long sequences of identical bits (0s) into very little space.",
    source: "GATE CS 2021"
  },
  {
    id: "pyq_5",
    question: "Assume a table has 1,000,000 rows. A column 'Marital_Status' has 4 distinct values. What is the approximate uncompressed size of the bitmap index for this column?",
    options: [
      "4 MB",
      "500 KB",
      "4000 Bytes",
      "32 MB"
    ],
    correctAnswerIndex: 1,
    explanation: "4 distinct values = 4 bitmaps. Each bitmap has 1,000,000 bits. Total = 4,000,000 bits. 4,000,000 bits / 8 = 500,000 bytes = 500 KB.",
    source: "BARC CS 2017"
  },
  {
    id: "pyq_6",
    question: "Consider a table 'Employees' with bitmap indexes on 'Department' (5 values) and 'Shift' (3 values). To find employees in 'Sales' OR on the 'Night' shift, how does the database evaluate this?",
    options: [
      "It scans the table sequentially checking both conditions.",
      "It performs a bitwise OR operation between the 'Sales' bitmap and the 'Night' bitmap.",
      "It performs a bitwise AND operation between the 'Sales' bitmap and the 'Night' bitmap.",
      "It uses a B-Tree index to find Sales, then scans for Night shift."
    ],
    correctAnswerIndex: 1,
    explanation: "The query uses an OR condition. The engine simply takes the bitmap for 'Department=Sales' and the bitmap for 'Shift=Night' and performs a fast hardware bitwise OR.",
    source: "GATE IT 2015"
  },
  {
    id: "pyq_7",
    question: "Which of the following is true regarding B-Tree indexes versus Bitmap indexes?",
    options: [
      "B-Trees are better for Data Warehouses, Bitmaps are better for OLTP.",
      "B-Trees are better for high-cardinality data, Bitmaps are better for low-cardinality data.",
      "B-Trees support fast COUNT() queries better than Bitmaps.",
      "Bitmaps use more memory than B-Trees for primary key columns."
    ],
    correctAnswerIndex: 1,
    explanation: "B-Trees are efficient when querying unique or high-cardinality data. Bitmaps are efficient when data has few distinct values (low cardinality).",
    source: "UGC NET CS 2020"
  },
  {
    id: "pyq_8",
    question: "A table T has a bitmap index on column C. If a new row is inserted into T, how many bitmaps in the index for C must be updated?",
    options: [
      "All bitmaps for column C must be updated by appending a new bit.",
      "Only the bitmap corresponding to the inserted value is updated.",
      "No bitmaps are updated until the index is rebuilt.",
      "The entire index is discarded and recreated."
    ],
    correctAnswerIndex: 0,
    explanation: "Because bitmaps map exactly to row positions, inserting a new row requires appending a bit (0 or 1) to ALL bitmaps for that column to maintain positional alignment.",
    source: "ISRO Scientist (CS) 2019"
  },
  {
    id: "pyq_9",
    question: "What is a 'Roaring Bitmap'?",
    options: [
      "A bitmap index that uses machine learning to predict queries.",
      "An uncompressed bitmap index used only in Oracle databases.",
      "A hybrid data structure that dynamically compresses bitmaps using arrays, runs, and uncompressed bitsets for high performance.",
      "A bitmap that is stored entirely in GPU memory."
    ],
    correctAnswerIndex: 2,
    explanation: "Roaring Bitmaps are a state-of-the-art compressed bitmap data structure that adaptively uses different storage containers (arrays, runs, bitsets) depending on density.",
    source: "GATE CS 2022"
  },
  {
    id: "pyq_10",
    question: "In a query checking 'A AND NOT B' where A and B have bitmap indexes, what bitwise operation is performed?",
    options: [
      "A XOR B",
      "A AND (NOT B)",
      "NOT (A AND B)",
      "A OR B"
    ],
    correctAnswerIndex: 1,
    explanation: "The engine first flips all bits in B (NOT B), and then performs a bitwise AND with A. This directly yields the rows satisfying 'A AND NOT B'.",
    source: "BARC CS 2021"
  }
];
